import dataoneimg from '../../assets/data1img.png';

const OrderData = [
  {
    id: 1,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 2,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'In progress'
  },
  {
    id: 3,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Dispatched'
  },
  {
    id: 4,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Paused'
  },
  {
    id: 5,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 6,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 7,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 8,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 9,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 10,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  },
  {
    id: 11,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Dispatched'
  },
  {
    id: 12,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'AO Disabled'
  },
  {
    id: 13,
    img: dataoneimg,
    sale: '-',
    source: 'Amazon',
    title: 'Title of the product',
    qty: '1',
    sold: '€15.99',
    cost: '€12.99',
    fees: '€1.00',
    profit: '€1.00',
    margin: '-',
    orderOn: '13/07/12:56',
    state: 'Error'
  }
];

export default OrderData;
