export const Links = {
  Dashboard: '/dashboard',
  Products: '/products',
  PublishNow: '/list-now',
  ManualPublish: '/manual-publish',
  BulkPublish: '/bulk-publish',
  Orders: '/orders',
  SourceSettings: '/sources-settings',
  SourcesSettingsTable: '/sources-table',
  ChannelSettings: '/channel',
  NewChannel: '/new-channel',
  Services: '/services',
  Subscriptions: '/subscriptions',
  Checkout: '/checkout',
  PaymentMethod: '/payment-method',
  PricingRules: '/pricing-rules',
  BrowserExtension: '/browser-extensions',
  VaProfiles: '/va-profiles',
  GetStarted: '/get-started',
  Catalog: '/catalog',
  Templates: '/templates',
  AutoOrderConfiguration: '/auto-ordering-configuration',
  Login: '/login',
  Register: '/register',
  ListingService: 'https://hustlegotreal.com/en/listing-service/',
  AutoOrderConfigurationQuery: '/auto-ordering-configuration-query' //<--What's this?
};