export const Links = {
  Dashboard: '/dashboard',
  Products: '/products',
  PublishNow: '/list-now',
  ManualPublish: '/manual-publish',
  BulkPublish: '/bulk-publish',
  Orders: '/orders',
  SourcesSettings: '/suppliers',
  ChannelSettings: '/channel-configuration',
  NewChannel: '/new-channel',
  Services: '/services',
  Subscriptions: '/subscriptions',
  OurServices: '/our-services',
  Checkout: '/checkout',
  PaymentMethod: '/payment-method',
  PricingRules: '/pricing-rules',
  BrowserExtension: '/browser-extensions',
  VaProfiles: '/va-profiles',
  GetStarted: '/get-started',
  Catalog: '/catalog',
  Templates: '/templates',
  EditTemplate: '/templates/edit/:id',
  AutoOrderConfiguration: '/auto-ordering-configuration',
  ConfigureNoapi: '/configure-no-api-server',
  ConfigureListingService: '/setup-preferences',
  Login: '/login',
  Register: '/register',
  PriceWarrior: '/price-warrior-configuration',
  ListingService: 'https://hustlegotreal.com/en/listing-service/',
  AutoOrderConfigurationQuery: '/auto-ordering-configuration-query' //<--What's this?
};
