
name: Build image and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
      - 'v*.*.*'

jobs:
  simple-job-for-reuse-workflow:
    uses: HustleGotReal/reusable-workflows/.github/workflows/dotnet-generic-deploy.yml@master
    with:
      DOCKER_IMAGEBASE: hustlegotreal/hgrweb
      DOCKER_FILEPATH: ./production.dockerfile
      DOCKER_CONTEXT_X: ./
      K8S_RESOURCENAME: hgrweb
      K8S_ADDITIONAL_RESOURCE: ""
      K8S_NAMESPACE: live
      K8S_OBJECTTYPE: deployment
      K8S_CONTAINERNAME: hgrweb
      #IGNOREME: true
    secrets:
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GPACKAGES_TOKEN: ${{secrets.GPACKAGES_TOKEN}}
      KUBECONFIG: ${{secrets.KUBECONFIG}}
